apiVersion: v1
kind: Service
metadata:
  name: katalogstrani-service
  labels:
    app: katalog-strani
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 32224
  selector:
    app: katalog-strani