apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: katalog-service-monitor
  labels:
    team: katalogteam
spec:
  selector:
    matchLabels:
      app: katalog-strani
  endpoints:
  - port: server